### ISSUE TITLE
[suggestion] Add compatibility for LethalRegeneration

### ISSUE THREAD

**Issue by ytitnE** [AndreyMrovol/LethalTerminalFormatter#1]
LethalRegeneration has a ship upgrade for health regeneration, and it doesn't show up in the shop catalogue. Would love to see it in there. Love the format, keep up the good work!

**Comment by AndreyMrovol** [comment]
Hey, thanks for making the request - I'll look into it 😅

**Comment by AndreyMrovol** [comment]
Hey, sorry for getting back to you so late - I've added compatibility with LethalRegeneration and it's buyable upgrade displays correctly in the terminal - please check the latest version in Thunderstore and let me know if there are any issues 😄

**Comment by ytitnE** [comment]
No worries, Awesome! Looking forward to it. Appreciate the hard work!

**Comment by ytitnE** [comment]
It seems the divide list set to 0 doesnt like it and gets rid of a lot of the list, saying [buyableitemlist] [unlockableselectionlist]

**Comment by ytitnE** [comment]
Disregard that, LLL was enabled and caused that, using LLLFixed works fine

**Comment by ytitnE** [comment]
Maybe not actually, idk how it worked before, but its not liking it with LLLfixed

**Comment by ytitnE** [comment]
Yeah, but I just tested and it doesnt like it when its set to 0, every other is fine. I can just set the number high and its fine. Just wanted you to be aware of it. I do have only LLLFixed on

**Comment by AndreyMrovol** [comment]
> Yeah, but I just tested and it doesnt like it when its set to 0, every other is fine. I can just set the number high and its fine. Just wanted you to be aware of it. I do have only LLLFixed on

The upgrade price?

**Comment by AndreyMrovol** [comment]
Yeah, i've checked - if the price is set to 0, it returns to the default value; if you set it to anything else it's gonna work and display correctly
![image](https://github.com/AndreyMrovol/LethalTerminalFormatter/assets/32998721/aa4101e4-be1b-4f96-8d2b-33169f1434d7)

**Comment by AndreyMrovol** [comment]
> It seems the divide list set to 0 doesnt like it and gets rid of a lot of the list, saying [buyableitemlist] [unlockableselectionlist]

oh fuck, i've not included a check for that 😥

**Comment by AndreyMrovol** [comment]
I've just pushed the update to Thunderstore, please check it out and let me know if it fixes your issues 😄

**Comment by ytitnE** [comment]
Oh I was talking about the divided lines being 0, the price was good for me, and the divided lines is all good now, appreciate all of your hardwork! Well done!
