### ISSUE TITLE
Compatibility with TerminalApi?

### ISSUE THREAD

**Issue by jacket430** [AndreyMrovol/LethalTerminalFormatter#10]
Hey there!

I've been using darmuhsTerminalStuff for a while as I really enjoy the set of features it has, but I was hoping I could use this mod to clean up the UI a bit but it doesn't seem to be compatible with it (or TerminalApi). I know it's probably a long shot, but if there was a way to have this UI with the extra commands added through TerminalApi, I'd love to see that. 

Thanks for reading, appreciate the hard work either way.

**Comment by AndreyMrovol** [comment]
> I was hoping I could use this mod to clean up the UI a bit but it doesn't seem to be compatible with it (or TerminalApi).


Hey, thanks for the report - what exactly is not working/conflicting?

**Comment by jacket430** [comment]
At least with my testing, running the two together causes the terminal to
become unusable, like you'll hear the sound of accessing the terminal but
you won't enter the animation, and after the sound plays you're no longer
able to interact with the computer at all.

If you're curious what my setup is, I have it being updated here as I work
on things for my friends.

https://gitgud.io/jacket430/430-company-modpack

**Comment by jacket430** [comment]
Hey there,

Not sure what you've done over the past few updates but upon checking today it appears the terminal is working totally fine!

Thanks a bunch! Great work :)
