### ISSUE TITLE
Compatibility with LethalQuantities

### ISSUE THREAD

**Issue by ProjectBots** [AndreyMrovol/LethalTerminalFormatter#15]
LethalQuantities allows one to change the moon route price and Risk Level.
LethalTerminalFormatter does not reflect those changes currently.

**Comment by AndreyMrovol** [comment]
Hey, thanks for the report - I'll get it working

**Comment by AndreyMrovol** [comment]
Hey, i've pushed an update to Thunderstore which should resolve your issue - please check it out!

**Comment by ProjectBots** [comment]
It works like a charm now! Thanks you
