### ISSUE TITLE
[Request] Option to show hidden routes (or compatibility with GeneralImprovements option)

### ISSUE THREAD

**Issue by ajsglist** [AndreyMrovol/LethalTerminalFormatter#17]
Hi there,

It would be great to have an option to always show the hidden moon routes.  GeneralImprovements has an option for this, but it doesn't work in conjunction with TerminalFormatter.

Thanks for the consideration

https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/issues/183

**Comment by AndreyMrovol** [comment]
Hey, thanks for the request - I'll look into this

**Comment by AndreyMrovol** [comment]
Hey, this has been added in v0.2.14 - please check it out and let me know!
