### ISSUE TITLE
[Request] "Divide moon page into groups"

### ISSUE THREAD

**Issue by ajsglist** [AndreyMrovol/LethalTerminalFormatter#20]
would it be possible to get a Moon catalog option analogous to the current "Divide shop page into groups" for the moon listings?

thanks for the consideration

**Comment by AndreyMrovol** [comment]
Hey, if you're using LLL you can set up exactly that in LLL's config 😅

**Comment by ajsglist** [comment]
I didn't realize it would use those settings, thanks!
