### ISSUE TITLE
The cost of the planets is not shown

### ISSUE THREAD

**Issue by Paradox75831004** [AndreyMrovol/LethalTerminalFormatter#4]
The cost of vanilla planets is not displayed in my build. Why?
![image](https://github.com/AndreyMrovol/LethalTerminalFormatter/assets/72872478/aefb190a-6a05-47c4-b50c-51fb56b7a78c)

Although it should be so
![image](https://github.com/AndreyMrovol/LethalTerminalFormatter/assets/72872478/a972eff7-ebba-4328-a543-aab0b6ed0541)
Maybe you need to change something in the config?

My build contains LLL and LE

**Comment by AndreyMrovol** [comment]
Hey, you're in `preview weather` mode - type `all` in terminal

**Comment by Paradox75831004** [comment]
Oh, I didn't know
Is there any way to do this by default in the config? So that you don't have to enter it every time. It's inconvenient

**Comment by Paradox75831004** [comment]
![image](https://github.com/AndreyMrovol/LethalTerminalFormatter/assets/72872478/fd20d363-3d8b-4cb6-8c55-5eb7f70d27e5)
If I put ALL here, does that mean everything will be the same?

**Comment by AndreyMrovol** [comment]
> Oh, I didn't know
> Is there any way to do this by default in the config? So that you don't have to enter it every time. It's inconvenient

My mod works with LLL's sort/preview/filter options, so you'll need to check it's config for default preview options

**Comment by Paradox75831004** [comment]
Can you push the config in the future to show the price of planets by default? @AndreyMrovol

**Comment by Paradox75831004** [comment]
![image](https://github.com/AndreyMrovol/LethalTerminalFormatter/assets/72872478/69364cff-a81e-4807-bc57-bf814c9639c9)
There is not enough space before S+, but these are small things

**Comment by AndreyMrovol** [comment]
> Can you push the config in the future to show the price of planets by default? @AndreyMrovol 

I think I could do something about it, but ultimately it's using LLL's options and config. 

I'll think of some way to handle this nicely.

**Comment by AndreyMrovol** [comment]
> ![image](https://github.com/AndreyMrovol/LethalTerminalFormatter/assets/72872478/69364cff-a81e-4807-bc57-bf814c9639c9)
> There is not enough space before S+, but these are small things

That's good to know, I'll fix it in next release

**Comment by Paradox75831004** [comment]
Is there compatibility with https://thunderstore.io/c/lethal-company/p/mrov/WeatherTweaks/
?
In this regard, he will also write - Unknown weather and all that, he just couldn't check in testing. It seems to work - it just replaces the vanilla weather value with its own

**Comment by AndreyMrovol** [comment]
> Is there compatibility with https://thunderstore.io/c/lethal-company/p/mrov/WeatherTweaks/
> ?
> In this regard, he will also write - Unknown weather and all that, he just couldn't check in testing. It seems to work - it just replaces the vanilla weather value with its own

There's full compatibility - those are both my mods.

**Comment by Paradox75831004** [comment]
> There's full compatibility - those are both my mods.

I'm sorry, I completely forgot >.<
The best mods, thank you very much for your work
(I test too much, I forget some points)

**Comment by AndreyMrovol** [comment]
No worries 😅

**Comment by Paradox75831004** [comment]
Yes, it was easier to put the DLL in the DLL and everything is normal. I'm sorry that I haven't fully explored this topic...
