### ISSUE TITLE
The Company's buying percentage shown on the Moon Catalogue screen is erroneous

### ISSUE THREAD

**Issue by Fl4sHNoX** [AndreyMrovol/LethalTerminalFormatter#5]
The buying percentage shown on the terminal is wrong:

![20240226234642_1](https://github.com/AndreyMrovol/LethalTerminalFormatter/assets/3759901/4f855780-3b50-4c58-a24e-7db69c938895)

I think it may be tied to the [BuyRateSettings](https://github.com/MoonJuiceDev/BuyRateSettings) mod which randomizes the buying percentage each day but I'm not certain.
(e.g. it should be 40% as it's shown on the alert within this screenshot)

**Comment by AndreyMrovol** [comment]
Hey, i've forgot to include that fix in my latest version - it's now fixed, please check it out!

**Comment by Fl4sHNoX** [comment]
Can confirm that after a quick test it does seem to be fixed, thanks a lot!
