### ISSUE TITLE
Custom moons are not showing anymore

### ISSUE THREAD

**Issue by douglas-srs** [AndreyMrovol/LethalTerminalFormatter#8]
Hello, after I updated the Explorations modpack to 2.3.0, whenever I type moons on the terminal it doesn't show the custom moons anymore and I get an error on the console. Help?

![image](https://github.com/AndreyMrovol/LethalTerminalFormatter/assets/1311994/2603a3f4-64f0-4d97-b918-13025a9781f1)

**Comment by douglas-srs** [comment]
It isn't this mod's fault after all, it's Bozoros moon mod!

**Comment by AndreyMrovol** [comment]
Hey, thanks for the report - I'm glad to hear that the issue is fixed, I'll check what caused it on Bozoros end
