### ISSUE TITLE
LLL is causing TerminalFormatter to break on v50

### ISSUE THREAD

**Issue by RatserX** [AndreyMrovol/LethalTerminalFormatter#9]
The LethalLevelLoader dependency is broken at the moment and it breaks the terminal completely on v50:
```
[Info   : Unity Log] Caught error while entering computer terminal. Exiting player from terminal. Error: System.NullReferenceException: Object reference not set to an instance of an object
  at LethalLevelLoader.Patches.TerminalLoadNewNode_Prefix (Terminal __instance, TerminalNode& node) [0x00001] in <519c156a8dbc4475bcf45d93d9f3cd0d>:IL_0001
  at (wrapper dynamic-method) Terminal.DMD<Terminal::LoadNewNode>(Terminal,TerminalNode)
  at (wrapper dynamic-method) Terminal.DMD<Terminal::BeginUsingTerminal>(Terminal)
[Info   : Unity Log] Quit terminal; inTerminalMenu true?: {playerScript.inTerminalMenu}
```

I frankly don't see LLL being updated anytime soon since the last update was in February, and the only thing that has grown since then are the number of issues. Would it be possible to remove LLL as a dependency, maybe?

**Comment by AndreyMrovol** [comment]
Hey, until LLL updates (hopefully today) I'm unable to fix that - **for now this mod is not gonna work on v50**

**Comment by AndreyMrovol** [comment]
When anything changes I'll let you know

**Comment by AndreyMrovol** [comment]
Hey @RatserX, i've updated the mod to work on v50 - currently i've disabled LLL patch (so the moon catalogue is using LLL's function) but when LLL updates i'll update my mod to use that 👍

**Comment by RatserX** [comment]
Thanks, the update worked fine. Just asking, LLL is only needed to get the info from custom moons (or patched content), right? Would it be possible to add a toggle in the config (obviously set as False by default) to just load the info from vanilla moons, skipping LLL entirely? For people that are only going to play on vanilla moons the current version works perfectly fine.

**Comment by RatserX** [comment]
Oh wait, I see what you did. Would it be possible to leave the call to `Nodes.MoonsNoLLL();` if LLL isn't present? Like I said, it's convenient for those that only play on vanilla moons.

**Comment by AndreyMrovol** [comment]
https://github.com/AndreyMrovol/LethalTerminalFormatter/blob/main/TerminalFormatter%2FPlugin.cs#L46-L58

NoLLL version is active when there's no LLL present, making it fully working in vanilla 😇

**Comment by RatserX** [comment]
> Hey @RatserX, i've updated the mod to work on v50 - currently i've disabled LLL patch (so the moon catalogue is using LLL's function) but when LLL updates i'll update my mod to use that 👍

Oh, I completely misunderstood what you said here. That is perfect then!
